INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (1, 'Académie d''Orléans-Tours', '21 Rue Saint Etienne', '45000', 'Orléans');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (2, 'Académie de Rennes', '96 Rue d''Antrain', '35700', 'Rennes');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (3, 'Académie de Normandie', '168 Rue Caponière', '14000', 'Caen');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (4, 'Académie d''Amiens', '20 Boulevard d''Alsace-Lorraine', '80000', 'Amiens');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (5, 'Académie de Lille', '144 rue de Bavay', '59000', 'Lille');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (6, 'Académie de Reims', '1 Rue Navier', '51100', 'Reims');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (7, 'Académie de Nancy-Metz', '2 Rue Philippe de Gueldres', '54000', 'Nancy');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (8, 'Académie de Strasbourg', '6 Rue de la Toussaint', '67000', 'Strasbourg');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (9, 'Académie de Besançon', '10 Rue de la Convention', '25000', 'Besançon');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (10, 'Académie de Dijon', '2 g Rue du General Delaborde', '21000', 'Dijon');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (11, 'Académie de Nantes', 'Chemin de la Houssinière', '44300', 'Nantes');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (12, 'Académie de Poitiers', '22 Rue Guillaume 7 le Troubadour', '86000', 'Poitiers');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (13, 'Académie de Limoges', '13 Rue François Chénieux', '87000', 'Limoges');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (14, 'Académie de Clermont-Ferrand', '3 Avenue Vercingétorix', '63000', 'Clermont-Ferrand');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (15, 'Académie de Lyon', '92 Rue de Marseille', '69007', 'Lyon');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (16, 'Académie de Grenoble', '7 Place Bir Hakeim', '38000', 'Grenoble');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (17, 'Académie d''Aix-Marseille', 'Place Lucien Paye', '13100', 'Aix-en-Provence');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (18, 'Académie de Nice', '53 Avenue Cap de Croix', '06100', 'Nice');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (19, 'Académie de Corse', 'Boulevard Pascal Rossini', '20000', 'Ajaccio');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (20, 'Académie de Montpellier', '31 Rue de l''Université', '34000', 'Montpellier');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (21, 'Académie de Toulouse', '75 Rue Saint Roch', '31400', 'Toulouse');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (22, 'Académie de Bordeaux', '5 Rue Joseph de Carayon Latour', '33000', 'Bordeaux');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (23, 'Académie de Mayotte', 'BP 76', '97600', 'Mayotte');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (24, 'Académie de Guyane', 'Route de Baduel', '97300', 'Cayenne');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (25, 'Académie de La Réunion', '24 Avenue Georges Brassens', '97400', 'Saint-Denis');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (26, 'Académie de Guadeloupe', 'Parc d''Activite Dothemare', '97139', 'Les Abymes');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (27, 'Académie de Martinique', 'Terreville', '97233', 'Schœlcher');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (28, 'Académie de Versailles', '3 Boulevard de Lesseps', '78000', 'Versailles');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (29, 'Académie de Paris', '12 Boulevard d''Indochine', '75019', 'Paris');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (30, 'Académie de Créteil', '4 Rue Georges Enesco', '94000', 'Créteil');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (31, 'Vice-rectorat de Wallis-et-Futuna', 'Mata Utu', '98609', 'Wallis et Futuna');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (32, 'Vice-rectorat de la Polynésie française', '25 avenue Pierre Loti BP 1632', '98713', 'Papeete - Tahiti');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (33, 'Vice-rectorat de Nouvelle-Calédonie', 'BP G 4', '98848', 'Nouméa Cedex');
INSERT INTO matools.academy (id, name, adress, zipcode, city) VALUES (34, 'Service de l''éducation nationale de Saint-Pierre et Miquelon', 'BP 4239', '97500', 'Saint-Pierre-et-Miquelon');