INSERT INTO matools.circo (id, district_id, name) VALUES (1, 6, 'Châteauneuf sur Loire');
INSERT INTO matools.circo (id, district_id, name) VALUES (2, 6, 'Fleury les Aubrais');
INSERT INTO matools.circo (id, district_id, name) VALUES (3, 6, 'Gien');
INSERT INTO matools.circo (id, district_id, name) VALUES (4, 6, 'Loiret ASH');
INSERT INTO matools.circo (id, district_id, name) VALUES (5, 6, 'Montargis Est');
INSERT INTO matools.circo (id, district_id, name) VALUES (6, 6, 'Montargis Ouest');
INSERT INTO matools.circo (id, district_id, name) VALUES (7, 6, 'Orléans Est');
INSERT INTO matools.circo (id, district_id, name) VALUES (8, 6, 'Orléans Saran');
INSERT INTO matools.circo (id, district_id, name) VALUES (9, 6, 'Orléans Sud');
INSERT INTO matools.circo (id, district_id, name) VALUES (10, 6, 'Orléans Val de Loire');
INSERT INTO matools.circo (id, district_id, name) VALUES (11, 6, 'Pithiviers');
INSERT INTO matools.circo (id, district_id, name) VALUES (12, 6, 'Saint Jean de la Ruelle');
INSERT INTO matools.circo (id, district_id, name) VALUES (13, 6, 'Saint Pryvé Saint Mesmin');